[tool:pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    -s
    --alluredir=./allure-results
    --strict-markers
markers =
    smoke: smoke tests (critical UI elements)
    regression: regression tests
filterwarnings =
    ignore::DeprecationWarning
    